### ISSUE TITLE
Automate your release pipeline to increase version and trigger release

### ISSUE THREAD

**Issue by easystartup-io** [tomsiewert/hetznercloud-java#177]
I see that after every merge you have to manually make changes in 3-4 files and push manually. This can be automated. Can you try following the links to add a github workflow which automatically increments the version and commits to the repo with a message [skip-ci-version-bump] so that it does not infinitely trigger version increments. Some sample links to check. 

1. https://blog.jakelee.co.uk/incrementing-version-automatically-after-release/
2. https://github.com/marketplace/actions/version-increment
3. https://github.com/marketplace/actions/find-and-replace
4. https://github.com/easystartup-io/k3s-simplified/blob/main/.github/workflows/build.yaml

**Comment by easystartup-io** [comment]
And you can add this to the actions workflow file so that it does not run concurrently, and only runs one after another. 
```
concurrency:
  group: ${{ github.workflow }}
```

**Comment by easystartup-io** [comment]
if you need help I can create a workflow for it

**Comment by tomsiewert** [comment]
I was and I am against automated releases after every merged PR, mainly because staging multiple or bigger changes is not that easy then anymore.

At this time I have a small Taskfile locally which bumps the version, pushes an MR and generates a tag.
