### ISSUE TITLE
getFirewall(long id) is not accessible

### ISSUE THREAD

**Issue by litetex** [tomsiewert/hetznercloud-java#190]
The method https://github.com/tomsiewert/hetznercloud-java/blob/258a15cc60928893ee780bcef748134d2a2f0bd6/src/main/java/me/tomsdevsn/hetznercloud/HetznerCloudAPI.java#L716 is private and can therefore not be accessed.

I think it should be public.

**Comment by tomsiewert** [comment]
🙈 

Thanks for reporting this and sending a PR.

**Comment by tomsiewert** [comment]
3.2.5 released with your fix. Apologies for the late response!
