### ISSUE TITLE
link to javadoc in readmy not working

### ISSUE THREAD

**Issue by jayjay86** [tomsiewert/hetznercloud-java#195]
In the readme, a link to javadoc is referenced, but when opening (https://docs.hcloud.siewert.io/) you get: There isn't a GitHub Pages site here.

Would be great to have a working link for browsing the javadoc online :)

**Comment by tomsiewert** [comment]
Thanks for the heads-up! Please try https://tomsiewert.github.io/hetznercloud-java/ 

I'll change that in the readme

**Comment by tomsiewert** [comment]
Issue fixed in #200 

Thanks again!
