### ISSUE TITLE
ImagesResponse not usable

### ISSUE THREAD

**Issue by sprinteins-ops** [tomsiewert/hetznercloud-java#196]
Hey, I try to use ImagesResponse Class, but as the member is private, it is unusable for forther processing (except converting to string).... 
Is it possible to add a getter for the images member?

**Comment by tomsiewert** [comment]
The getters are being generated via Lombok with the `@Data` annotation.

Do you get an error or similar in your IDE?

**Comment by sprinteins-ops** [comment]
Hey, thanks for the hint, it seems my IDE was kind of stuck. Works like charm :)
