### ISSUE TITLE
Missing API error codes are causing exception.

### ISSUE THREAD

**Issue by n0ise9914** [tomsiewert/hetznercloud-java#206]
According to the Hetzner Cloud API [documentation](https://docs.hetzner.cloud/#errors), these two API error codes are missing.
[unavailable, unauthorized]

I did also make a PR ([https://github.com/tomsiewert/hetznercloud-java/pull/207](https://github.com/tomsiewert/hetznercloud-java/pull/207)), hope get merged soon

**Comment by tomsiewert** [comment]
Will be fixed with v3.2.7. I need to fix the traffic changes [1] first and will create a git release afterwards.

[1] https://docs.hetzner.cloud/changelog#2024-07-25-cloud-api-returns-traffic-information-in-different-format
