### ISSUE TITLE
Replace Spring with a more lightweight HTTP library

### ISSUE THREAD

**Issue by tomsiewert** [tomsiewert/hetznercloud-java#74]
Hey, would you be ok with replacing Spring with a more lightweight HTTP only library (e.g. OkHttp)? 

Currently only the Resttemplate is used from Spring, which in my opinion drags in a lot of complexity and dependencies just to execute some basic HTTP requests. Spring, being a fairly complex  piece of software with a lot of dependencies also greatly increases the attack surface (see CVEs for currently used version) and makes usage in a Spring application potentially harder.

_Originally posted by @pellepelster in https://github.com/TomSDEVSN/hetznercloud-java/discussions/45#discussioncomment-2856117_

**Comment by pellepelster** [comment]
see PR https://github.com/tomsiewert/hetznercloud-java/pull/75

**Comment by pellepelster** [comment]
closed by https://github.com/tomsiewert/hetznercloud-java/pull/75
